### ISSUE TITLE
Wrong dataset link in README.md

### ISSUE THREAD

**Issue by hist0613** [KAIST-CHATGPT-TEAM1/CLICK#2]
current: [https://huggingface.co/datasets/your_username/CLIcK](https://huggingface.co/datasets/your_username/CLIcK)
it needs to be changed into: [https://huggingface.co/datasets/scottsuk0306/CLIcK](https://huggingface.co/datasets/scottsuk0306/CLIcK)

**Comment by juyoungml** [comment]
Thank you for pointing out! We fixed the link.
