### ISSUE TITLE
Inquiry about Dataset Split

### ISSUE THREAD

**Issue by taeminlee** [KAIST-CHATGPT-TEAM1/CLICK#3]
Hello,

Thank you for sharing such an excellent dataset.

The evaluation of Korean models is always a challenging topic, and the information you have provided is greatly beneficial for the development of Korean LLMs.

I have one question I'd like to ask.

Generally, datasets are divided into train, validation, and test splits, and when using them for model evaluation, the validation and test splits are typically used.

For example:

https://huggingface.co/datasets/Rowan/hellaswag
https://huggingface.co/datasets/klue

In the case of the dataset shared on Huggingface, only the train split is present, so I am curious if the current publicly available dataset is a part of a larger dataset.

If the dataset was developed for evaluation purposes only, would it be possible to change the split from train to validation or test in the Huggingface datasets?

**Comment by taeminlee** [comment]
I have slightly modified the dataset you shared and divided it into various subsets and setting them as test splits.

The README.md file in my [CLIcK dataset repository](https://huggingface.co/datasets/taeminlee/CLIcK) contains the necessary information to create these splits and subsets.

Creating these subsets will facilitate a more comprehensive evaluation of different aspects of the data.

**Comment by juyoungml** [comment]
Thanks for your suggestion! We'll definitely update the dataset format in few days :)

**Comment by taeminlee** [comment]
Thank you for your response. I look forward to the updated version. :)
